spring:
  main:
    banner-mode: "off"
  application:
    name: dynamo-example
  webflux:
    base-path: /dynamo
  flyway:
    url: jdbc:postgresql://db:5432/postgres
    user: postgres
    password: postgres
    default-schema: postgres
    enabled: ${FLYWAY_ENABLED:false}
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

dynamo-api:
  enabled: true
  database:
    postgres:
      host: ${POSTGRES_DB_HOST:localhost}
      port: ${POSTGRES_DB_PORT:5432}
      database: ${POSTGRES_DB_DATABASE:postgres}
      user: ${POSTGRES_DB_USER:postgres}
      password: ${POSTGRES_DB_PASSWORD:postgres}
    dynamo:
      host: ${DYNAMO_DB_HOST:http://wrong-host:8000}
      region: ${DYNAMO_DB_REGION:localhost}
      access-key: ${DYNAMO_DB_ACCESS_KEY:randomKey}
      access-id: ${DYNAMO_DB_ACCESS_ID:randomKey}
